version: "3"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
networks:
  hostnet:
    external:
      name: host