version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/nginx.conf.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
        reservations:
          cpus: '0.02'
          memory: 50M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm start"
    depends_on:
      - nginx
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  hostnet:
    external:
      name: host
