version: "3"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  hostnet:
    external:
      name: host
